all: i1040sd--2017.pdf i1040gi--2017.pdf i1040sb--2017.pdf

i1040sd--2017.pdf:
	wget https://www.irs.gov/pub/irs-prior/i1040sd--2017.pdf

i1040gi--2017.pdf:
	wget https://www.irs.gov/pub/irs-prior/i1040gi--2017.pdf

i1040sb--2017.pdf:
	wget https://www.irs.gov/pub/irs-prior/i1040sb--2017.pdf
